import scroll from "./modules/scroll.js";
import servicesModal from "./modules/servicesModal.js";
import modalRequest from "./modules/modalRequest.js";
import timer from "./modules/timer.js";
import validateForm from "./modules/validateForm.js";
import sendForm from "./modules/sendForm.js";
scroll();
servicesModal();
modalRequest();
timer("21 may 2024");
validateForm();
sendForm();